//
//  ArtistViewModel.swift
//  myArt
//
//  Created by Oriane Batteux on 21/10/2024.
//

import Foundation

class ArtistViewModel: ObservableObject {
    
    @Published var artists: [Artist] = [
        Artist(id: 1, lastname: "De Vinci", firstname: "Léonard", birthdate: "04/15/1452", artistAlive: false, artisticMovement: "Renaissance", biography: "Leonardo da Vinci lived during the late 15th Century and early 16th Century in and around Italy. He was a painter, a scientist, an inventor, and an engineer. He is considered by historians to be a natural genius. Today he is best remembered for his art, especially the 'Mona Lisa' and the 'Last Supper'.", image: "devinci.jpg"),
        Artist(id: 2, lastname: "Matisse", firstname: "Henri", birthdate: "12/31/1869", artistAlive: false, artisticMovement: "Fauvism", biography: "was a French visual artist, known for both his use of colour and his fluid and original draughtsmanship. He was a draughtsman, printmaker, and sculptor, but is known primarily as a painter. Matisse is commonly regarded, along with Pablo Picasso, as one of the artists who best helped to define the revolutionary developments in the visual arts throughout the opening decades of the twentieth century, responsible for significant developments in painting and sculpture." , image: "matisse.jpg"),
        Artist(id: 3, lastname: "Picasso", firstname: "Pablo", birthdate: "04/08/1881", artistAlive: false, artisticMovement: "Cubism", biography: "As a significant influence on 20th-century art, Pablo Picasso was an innovative artist who experimented and innovated during his 92-plus years on earth. He was not only a master painter but also a sculptor, printmaker, ceramics artist, etching artist and writer. His work matured from the naturalism of his childhood through Cubism, Surrealism and beyond, shaping the direction of modern and contemporary art through the decades. Picasso lived through two World Wars, sired four children, appeared in films and wrote poetry. He died in 1973.", image: "picasso.jpg"),
        Artist(id: 4, lastname: "Kusama", firstname: "Yayoi", birthdate: "03/22/1929", artistAlive: true, artisticMovement: "Contemporain", biography: "Is a Japanese artist who is a self-described “obsessional artist,” known for her extensive use of polka dots and for her infinity installations. She employed painting, sculpture, performance art, and installations in a variety of styles, including Pop art and Minimalism. By her own account, Kusama began painting as a child, at about the time she began experiencing hallucinations that often involved fields of dots. Those hallucinations and the theme of dots would continue to inform her art throughout her career. She had little formal training, studying art only briefly (1948–49) at the Kyōto City Specialist School of Arts. Family conflict and the desire to become an artist drove her to move in 1957 to the United States, where she settled in New York City. Before leaving Japan, she destroyed many of her early paintings.", image: "kusama.jpg"),
        Artist(id: 5, lastname: "Rothko", firstname: "Mark", birthdate: "09/25/1903", artistAlive: false, artisticMovement: "Expressivism", biography: "Mark Rothko was born in Russia and immigrated to the United States with his family in his youth. In the mid-20th century, he belonged to a circle of New York-based artists (also including Willem de Kooning and Jackson Pollock) who became known as the Abstract Expressionists. His signature works, large-scale paintings of luminous colored rectangles, used simplified means to evoke emotional responses. Rothko committed suicide on February 25, 1970.", image: "rothko.jpg"),
        Artist(id: 6, lastname: "Fish", firstname: "Julia", birthdate: "1950", artistAlive: true, artisticMovement: "", biography: "Julia Fish (b. 1950, Toledo, OR) has been the subject of twenty-nine solo exhibitions since 1980, and has twice been the subject of ‘ten-year’ survey exhibitions: most recently, Julia Fish : bound by spectrum, DePaul Art Museum, Chicago, 2019-2020; and View, The Renaissance Society, University of Chicago, 1996. Selected curated exhibitions include, among others: The American Academy of Arts and Letters, New York, NY; The Menil Collection, Houston, TX; San Francisco Museum of Modern Art; MAK Center for Art and Architecture / Schindler House, Los Angeles; Tang Museum, Skidmore College, Saratoga Springs, NY; Martin Gropius Bau, Berlin; Galerie Remise, Bludenz, Austria; the Whitney Biennial; and the MCA Chicago.", image: "fish.jpg"),
        Artist(id: 7, lastname: "Kavi", firstname: "Emmanuel", birthdate: "03/03/1970", artistAlive: true, artisticMovement: "Abstract", biography: "Emmanuel Kavi was born on 3 March 1970 in Lomé, Togo. A self-taught painter, Kavi began with drawing and illustration. In 1987, at 17 years old, he won a national drawing contest in Togo. Progressively, his style evolved towards the abstract. In 2001 he began to exhibit, first in West Africa and then in Europe, where his style is sometimes termed 'African cubism'.", image: "kavi.jpg"),
        Artist(id: 8, lastname: "Haider Raza", firstname: "Sayed", birthdate: "02/22/1922", artistAlive: true, artisticMovement: "Modernist", biography: "His early works include landscapes, and later moved towards abstraction as he became increasingly influenced by Modernist principles. 1970 was a turning point in Raza’s career, when he developed the concept of Bindu (a personal rebirth) in his art. The works from this period are more intricately linked to Indian roots and cultural themes, and were influenced by his trips back to India. Raza is a founder of the Raza Foundation in India, which gives away the Annual Raza Foundation Award to emerging artists. In 2010, Christie’s sold his work Saurashtra for US$3.4 million, a record-breaking price for a living Indian artist. His work has been exhibited at the National Gallery of Modern Art in New Delhi, and is part of many international collections.", image: "haider.jpg")
    ]
}
